# Generated by Django 3.1.6 on 2021-02-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210223_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodcut',
            name='description',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
